### ISSUE TITLE
loader3d: No such file or directory (../src/libcore/result.rs:736)

### ISSUE THREAD

**Issue by 0joshuaolson1** [sebcrozet/nrays#1]
Loading the scene.
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:736

Where did libcore go in the process of development?

**Comment by sebcrozet** [comment]
This error is probably not about libcore. It is more likely to be about missing assets. Did you follow the instructions given by the [readme](https://github.com/sebcrozet/nrays#3d-ray-tracing) (about wget-ing the assets) ?

**Comment by 0joshuaolson1** [comment]
Nope! Not at all! Will close if all's fine, sorry.
